identifier: default
image_type: GRAYSCALE
model: vgg16
target_shape: [64, 64]
pooling: max
random_seed: 36
train_split: 0.8  # training/validation ratio
validation_split: 0.1
training_epochs: 20
batch_size: 8
optimizer: rmsp # Not used yet (optimizer)
learning_rate: 1.0e-6
decay_rate: 0.97 # Not used yet (optimizer)
loss: binary_crossentropy
image_preprocessing:
  rescale: 0.003921568627 # rescale all inputs by 1/255
  horizontal_flip: True
  vertical_flip: True