identifier: inceptionv3
image_type: GRAYSCALE
model: inceptionv3
target_shape: [325, 325]
random_seed: 37
# training/validation ratio
train_split: 0.8
validation_split: 0.2
training_epochs: 50
# fine_tune: 
#   layers: [conv2d_94]
#   epochs: 50
#   learning_rate: 1.0e-5
batch_size: 16
learning_rate: 1.0e-5
loss: binary_crossentropy
image_preprocessing_train:
  rescale: 0.003921568627
  horizontal_flip: True
  vertical_flip: True
  samplewise_center: True
  zca_whitening: True
image_preprocessing_test:
  rescale: 0.003921568627
  samplewise_center: True
  zca_whitening: True