identifier: default
image_type: GRAYSCALE
model: vgg16
target_shape: [48, 48]
pooling: max
random_seed: 36
train_split: 0.5  # training/validation ratio
validation_split: 0.25
batch_size: 8
optimizer: rmsp
learning_rate: 1.0e-4
decay_rate: 0.97
test_interval: 1
loss: binary_crossentropy
image_preprocessing:
  rescale: 0.003921568627 # rescale all inputs by 1/255
  horizontal_flip: True
  vertical_flip: True
sample_to_batch_config:
  upscale_to_target: True
  always_sample_center: False # Randomized sampling