identifier: inception_v3_zca_samplewise
image_type: GRAYSCALE
model: inceptionv3
target_shape: [300, 300]
random_seed: 29
train_split: 0.8  # training/validation ratio
validation_split: 0.2
training_epochs: 150
batch_size: 16
learning_rate: 1.0e-4
loss: binary_crossentropy
image_preprocessing_train:
  rescale: 0.003921568627 # rescale all inputs by 1/255
  horizontal_flip: True
  vertical_flip: True
  samplewise_center: True
  zca_whitening: True
image_preprocessing_test:
  rescale: 0.003921568627 # rescale all inputs by 1/255
  samplewise_center: True
  zca_whitening: True